DocLocker/urls.py
"""
Definition of urls for DocLocker.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
# from django.conf.urls import include
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^home$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about', app.views.about, name='about'),
    url(r'^signup', app.views.signup, name='signup'),
    url(r'^uploadDoc', app.views.uploadDoc, name='uploadDoc'),
    url(r'^downloadDoc', app.views.downloadDoc, name='downloadDoc'),
    url(r'^login', app.views.login, name='login'),
    url(r'^logout', app.views.logout, name='logout'),
    url(r'^twoFactor', app.views.twoFactor, name='twoFactor'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
]

app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.utils.translation import ugettext_lazy as _

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=30,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))

class BootstrapSignupForm(UserCreationForm):
    """SignUp form which uses boostrap CSS."""
    username = forms.CharField(max_length=30,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'User name'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Password'}))
    confirmPassword = forms.CharField(label=_("Password confirmation"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Repeat password'}))
    phoneNumber = forms.CharField(label=_("Phone Number"),
                               widget=forms.NumberInput({
                                   'class': 'form-control',
                                   'placeholder':'Ex : 0606060606'}))
    passphrase = forms.CharField(label=_("Secret passphrase"),
                                 max_length=255,
                                 widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder':'Ex: Once upon a time...'}))

class BootstrapValidationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    code = forms.CharField(label=_("Code"),
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder':'123456'}))

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Use this area to provide additional information.</p>

{% endblock %}

app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

{% endblock %}

app/templates/app/downloadDoc.html
{% extends "app/layout.html" %}

{% block content %}
<script type="text/javascript">
    function deleteDocId(id) {
        document.getElementById('deleteDoc').value = '1';
        updateDocId(id);
    }
    function updateDocId(id) {
        document.getElementById('docId').value = id;
        document.uploadForm.submit();
        document.getElementById('passphrase').value = ''
    }
</script>

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="downloadDocForm">
            <form action="" method="post" name="uploadForm" class="form-horizontal" enctype="multipart/form-data">
                {% csrf_token %}
                <h4>Manage Doc</h4>
                <div class="form-group">
                    <label for="passphrase" class="col-md-2 control-label">Passphrase</label>
                    <div class="col-md-10">
                        <input type="text" class="form-control" autocomplete="off" id="passphrase" name="passphrase" maxlength="255" placeholder="Enter your secret passphrase" />
                    </div>
                </div>
                <hr />
                {{tableFiles |safe }}
                <input name="docId" id="docId" type="hidden" value="0" />
                <input name="deleteDoc" id="deleteDoc" type="hidden" value="0" />
                {% if msgError %}
                {% for member in msgError %}
                <p class="validation-summary-errors">{{ member }}</p>
                {% endfor %}
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}
{% load staticfiles %}
{% block content %}

<img src="{% static 'app/yoGDi9q.png' %}" width="100%" alt="DocLock">

<div class="row">
    <div class="col-md-4">
        <h2>Signing up</h2>
        <p>
            Signing up gives you the opportunity to have an account, which is necessary to visit the website and upload documents.
            A valid phone number is necessary to open an account.
        </p>
        <p><a class="btn btn-default" href="/signup">Sign up &raquo;</a></p>
    </div>
    {% if request.session.validated %}
    <div class="col-md-4">
        <h2>Uploading documents</h2>
        <p>Upload documents and files safely right now.</p>
        <p><a class="btn btn-default" href="/uploadDoc">Start uploading &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Logging out</h2>
        <p>Wish to leave? 
        Simply click this button, all your authentication data will be flushed</p>
        <p><a class="btn btn-default" href="/logout">Leave safely &raquo;</a></p>
    </div>
    {% else %}
    <div class="col-md-4">
        <h2>Logging in</h2>
        <p>Already have an account? Get your phone (2FA) and log-in</p>
        <p><a class="btn btn-default" href="/login">Learn more &raquo;</a></p>
    </div>
    {% endif %}
</div>

{% endblock %}

app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - My Django Application</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">DocLocker</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'uploadDoc' %}">Upload File</a></li>
                    <li><a href="{% url 'downloadDoc' %}">Manage Files</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - DocLocker</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="" method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if msgError %}
                {% for member in msgError %}
                <p class="validation-summary-errors">{{ member }}</p>
                {% endfor %}
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/loginpartial.html
<ul class="nav navbar-nav navbar-right">
    {% if request.session.validated %}
    <li><span class="navbar-brand">Connected as : {{request.session.username}}</span></li>
    {% endif %}
    {% if not request.session.validated %}
    <li><a href="{% url 'signup' %}">Sign up</a></li>
    {% endif %}
    {% if request.session.validated %}
    <li><a href="{% url 'logout' %}">Log out</a></li>
    {% else %}
    <li><a href="{% url 'login' %}">Log in</a></li>
    {% endif %}
</ul>

app/templates/app/signup.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="signupForm">
            <form action="" method="post" class="form-horizontal" autocomplete="off">
                {% csrf_token %}
                <h4>Fill the form to sign up</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password_confirm" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.confirmPassword }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_phone" class="col-md-2 control-label">Phone number (2-FA)</label>
                    <div class="col-md-10">
                        {{ form.phoneNumber }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="passphrase" class="col-md-2 control-label">Secret passphrase</label>
                    <div class="col-md-10">
                        {{ form.passphrase }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Sign up" class="btn btn-default" />
                    </div>
                </div>
                {% if msgError %}
                {% for member in msgError %}
                <p class="validation-summary-errors">{{ member }}</p>
                {% endfor %}
                {% endif %}
                {% if successfulCreation %}
                <p class="validation-summary-valid">Account successfully created </p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/twoFactor.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="ValidationForm">
            <form action="" method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>A text message was sent on your mobile phone.</h4>
                <h4>Enter your verification code to proceed.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_code" class="col-md-2 control-label">Code</label>
                    <div class="col-md-10">
                        {{ form.code }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Validate" class="btn btn-default" />
                    </div>
                </div>
                {% if msgError %}
                {% for member in msgError %}
                <p class="validation-summary-errors">{{ member }}</p>
                {% endfor %}
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

app/templates/app/uploadDoc.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="uploadDocForm">
            <form action="" method="post" class="form-horizontal" enctype="multipart/form-data">
                {% csrf_token %}
                <h4>Upload Doc</h4>
                <hr />
                <div class="form-group">
                    <label for="id_uploadDoc" class="col-md-2 control-label">file</label>
                    <div class="col-md-10">
                       <input type="file" name="myfile">
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Upload" class="btn btn-default" />
                    </div>
                </div>
                {% if msgError %}
                {% for member in msgError %}
                <p class="validation-summary-errors">{{ member }}</p>
                {% endfor %}
                {% endif %}
                {% if successfulUpload %}
                <p class="validation-summary-valid">File successfully uploaded! </p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}